foo:
  enabled: true
  remote-address: 1.1.1.1
spring:
  application:
    name: spring-workshop
#  datasource:
#    url: jdbc:h2:mem:test_db
#    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: create
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    enabled: false